[package]
name = "leetcode"
version = "0.1.0"
edition = "2018"
authors = ["cb.kris.bj@gmail.com"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"